"""add_github_pr_url_to_tickets

Revision ID: 77bb8a27120b
Revises: c85b627ccb2d
Create Date: 2026-06-28 01:27:53.375205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77bb8a27120b'
down_revision = 'c85b627ccb2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_pr_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('github_pr_url')

    # ### end Alembic commands ###
