"""add_team_mappings_table

Revision ID: d2cc5fc0deb3
Revises: 30d956daca64
Create Date: 2026-06-01 12:48:08.070202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2cc5fc0deb3'
down_revision = '30d956daca64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    # ### end Alembic commands ###

    # Seed default team mappings
    from datetime import datetime
    bind = op.get_bind()
    
    default_mappings = {
        'Software Issue': 'Software Team',
        'Hardware Issue': 'Hardware Team',
        'Network Issue': 'Network Team',
        'Email Issue': 'IT Support'
    }
    
    for category, team_name in default_mappings.items():
        res = bind.execute(sa.text("SELECT id FROM teams WHERE name = :name"), {"name": team_name}).fetchone()
        if res:
            team_id = res[0]
        else:
            bind.execute(sa.text("INSERT INTO teams (name, created_at) VALUES (:name, :created_at)"), 
                         {"name": team_name, "created_at": datetime.utcnow()})
            res = bind.execute(sa.text("SELECT id FROM teams WHERE name = :name"), {"name": team_name}).fetchone()
            team_id = res[0]
            
        map_res = bind.execute(sa.text("SELECT id FROM team_mappings WHERE category = :category"), {"category": category}).fetchone()
        if not map_res:
            bind.execute(sa.text("INSERT INTO team_mappings (category, team_id, created_at) VALUES (:category, :team_id, :created_at)"),
                         {"category": category, "team_id": team_id, "created_at": datetime.utcnow()})



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_mappings')
    # ### end Alembic commands ###
