"""Allow system status changes

Revision ID: d875a917d882
Revises: d52eea373c05
Create Date: 2026-02-19 16:34:32.057216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd875a917d882'
down_revision = 'd52eea373c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_status_history', schema=None) as batch_op:
        batch_op.alter_column('changed_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_status_history', schema=None) as batch_op:
        batch_op.alter_column('changed_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
